[tool.poetry]
name = "file_storage"
version = "0.1.0"
description = ""
authors = ["meetkira <kristi.2001@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
